Update Name Request Front Page #8715
bcgov/namerequest pull request #457
Opened 2021-09-14 22:22 UTC by eve-git

*Issue #:* /bcgov/entity#8715

*Description of changes:*

In the name request page:
1. put the list item (options) of a dropdown under the select input, instead of on the select input
2. change0 the color of an unselected list item to #495057
3. change the Jurisdiction list item text of 'BC' to 'British Columbia'

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of the namerequest license (Apache 2.0).

2021-09-14 23:38 UTC, cameron-freshworks commented on src/components/common/names-capture.vue
> +        <v-col cols="5" class="py-0">
i believe you still want an indent here as the `v-col` is a child element of the `v-row`.

2021-09-14 23:40 UTC, cameron-freshworks commented on src/components/new-request/search.vue
> +    color: #495057 !important;
You can use a predefined theme colour opposed to the hex here, i believe this is `$gray7`.

2021-09-14 23:41 UTC, cameron-freshworks reviewed
Looks good! Just a few minor things :)

2021-09-15 00:14 UTC, andrepestana-aot requested changes

2021-09-15 00:14 UTC, andrepestana-aot commented on src/components/new-request/search.vue
> +                       @change="clearErrors()"
There's an issue with the indentation here as well.

2021-09-15 17:38 UTC, eve-git commented
@cameron-freshworks @andrepestana-aot please review again. Thanks!

2021-09-15 17:40 UTC, andrepestana-aot approved these changes
Looks good!

2021-09-15 18:00 UTC, cameron-freshworks approved these changes
Looks good!

2021-09-15 18:01 UTC, merged