18068 - Namerequest UI: Editing the Resubmit NR has the first name choice as empty.
bcgov/namerequest pull request #740
Opened 2023-10-26 16:26 UTC by Rajandeep98

*Issue #18068 - Namerequest UI: Editing the Resubmit NR has the first name choice as empty.

*Description of changes:*
Updated condition for applying designation for resubmission for SP/GP

2023-10-26 16:27 UTC, Rajandeep98 commented
/gcbrun

2023-10-26 16:30 UTC, bcregistry-sre commented
Temporary Url for review: https://namerequest-dev--pr-740-qail5x3t.web.app

2023-10-26 17:09 UTC, severinbeauvais approved these changes
LGTM

2023-10-26 18:47 UTC, severinbeauvais requested changes
Removing my approval -- I didn't looks closely enough at the code. The code change will always be True because it's not comparing the NR's type with an enum; it's looking at the truthiness of the enums directly, which is always True.

Rajandeep and I looked at this together and we're not sure why this code exists -- can't the designation from the original NR simply be copied in to the new NR? This code suggests that some  NRs have a designation in the name but the designation field is empty. It would be good to have an example. We could then handle those specially.

The other option of exempting some types that we know don't have designations is less optimal but is probably safe and could be implemented as a last resort.

2023-10-27 22:33 UTC, Rajandeep98 commented
/gcbrun

2023-10-27 22:36 UTC, bcregistry-sre commented
Temporary Url for review: https://namerequest-dev--pr-740-qail5x3t.web.app

2023-10-27 22:37 UTC, severinbeauvais commented on src/store/actions.ts
> +  }
I'd name the flag something useful.

Also, you can simplify this...
```
const flag = (your boolean statement)
```

2023-10-27 22:37 UTC, severinbeauvais commented on src/store/actions.ts
> +  }
Thanks for the very useful comment!

2023-10-27 22:38 UTC, severinbeauvais approved these changes
I approve this solution.

2023-10-27 22:44 UTC, eve-git approved these changes

2023-10-27 22:49 UTC, severinbeauvais commented
Do not merge this until after the release on Tuesday, October 31.

2023-10-30 16:07 UTC, Rajandeep98 commented
/gcbrun

2023-10-30 16:08 UTC, severinbeauvais commented on src/store/actions.ts
> +  }
Thanks for the update. Sorry for being so picky. Your code looks good and I've approved this PR but I think you have to wait a couple of days before merging it (check with Omid).

2023-10-31 21:22 UTC, ozamani9gh approved these changes
looks good

2023-10-31 21:26 UTC, Rajandeep98 commented
/gcbrun

2023-10-31 21:29 UTC, bcregistry-sre commented
Temporary Url for review: https://namerequest-dev--pr-740-qail5x3t.web.app

2023-10-31 21:37 UTC, merged